from src.utils import os

ROOT_DIR = os.getcwd()
DATA_DIR = "data"
PROCESSED_DIR = "processed"
RAW_DATA_DIR = "raw"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"


PROCESSED_DIR_PATH = os.path.join(ROOT_DIR, DATA_DIR, PROCESSED_DIR)
RAW_DATA_DIR_PATH = os.path.join(ROOT_DIR, DATA_DIR, RAW_DATA_DIR)

PROCESSED_TRAIN_FILE_PATH = os.path.join(PROCESSED_DIR_PATH, TRAIN_FILE_NAME)
PROCESSED_TEST_FILE_PATH = os.path.join(PROCESSED_DIR_PATH, TEST_FILE_NAME)

RAW_TRAIN_DATA_PATH = os.path.join(RAW_DATA_DIR_PATH, TRAIN_FILE_NAME)
RAW_TEST_DATA_PATH = os.path.join(RAW_DATA_DIR_PATH, TEST_FILE_NAME)
